project/members/urls.py
from django.conf.urls import patterns, url

from .views import MemberCreateView, MemberDetailView, MemberListView

urlpatterns = patterns('',
    url(r'^add/$', MemberCreateView.as_view(), name='member_create'),
    url(r'^(?P<pk>[0-9]+)/$', MemberDetailView.as_view(), name='member_detail'),
    url(r'$', MemberListView.as_view(), name='member_list'),
)

project/personal_shoppers/urls.py
from django.conf.urls import patterns, url
from personal_shoppers.views import PersonalShopperUpdateView

from .views import PersonalShopperCreateView, PersonalShopperDetailView, PersonalShopperListView

urlpatterns = patterns('',
    url(r'^add/$', PersonalShopperCreateView.as_view(), name='p_shopper_create'),
    url(r'^(?P<pk>[0-9]+)/$', PersonalShopperDetailView.as_view(), name='p_shopper_detail'),
    url(r'^update/(?P<pk>[0-9]+)/$', PersonalShopperUpdateView.as_view(), name='p_shopper_update'),
    url(r'$', PersonalShopperListView.as_view(), name='p_shopper_list'),
)

project/project_settings/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from members.views import MemberListView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^personal_shoppers/', include('personal_shoppers.urls')),
    url(r'^members/', include('members.urls')),
    url(r'$', MemberListView.as_view(), name="home"),
)

project/members/models.py
from django.core.urlresolvers import reverse
from django.db import models
from personal_shoppers.models import PersonalShopper
from regions.models import Region


def assign_personal_shopper(region):
    #Exclude inactive personal shoppers and keep those only in the selected region
    personal_shoppers = PersonalShopper.objects.exclude(is_active=False).filter(regions__in=[region])

    #Order by least amount of leads
    shoppers = [
        #[personal_shopper, leads],
    ]
    for personal_shopper in personal_shoppers:
        leads = personal_shopper.member_set.filter(ordered_recently=False).count()
        shoppers.append([personal_shopper, leads])

    #Get the shopper with least amount of leads
    shoppers.sort(key=lambda x: x[1])
    return shoppers[0][0]


class Member(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.BigIntegerField(blank=True, null=True)
    region = models.ForeignKey(Region)
    personal_shopper = models.ForeignKey(PersonalShopper, blank=True, null=True)
    ordered_recently = models.BooleanField(default=False)  # check this with a cronjob

    def save(self, *args, **kwargs):
        if not self.personal_shopper:
            #Assign to personal shopper with least leads
            self.personal_shopper = assign_personal_shopper(self.region)
        super(Member, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s %s" % self.first_name, self.last_name

    def get_absolute_url(self):
        return reverse('member_detail', args=[str(self.pk)])


class Order(models.Model):
    """
    Simulate ordered boxes to generate leads
    """
    member = models.ForeignKey(Member)
    order_date = models.DateField()

project/personal_shoppers/models.py
from django.core.urlresolvers import reverse
from django.db import models
from regions.models import Region


class PersonalShopper(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    regions = models.ManyToManyField(Region, null=True, blank=True)

    def __unicode__(self):
        return "%s %s" % self.first_name, self.last_name

    def get_absolute_url(self):
        return reverse('p_shopper_detail', args=[str(self.pk),])

project/regions/models.py
from django.db import models
from django.contrib import admin


class Region(models.Model):
    name = models.CharField(max_length=25)
    tva_percentage = models.FloatField()

    def __unicode__(self):
        return self.name


admin.site.register(Region)

project/members/forms.py
from django import forms
from .models import Member


class MemberForm(forms.ModelForm):

    class Meta:
        model = Member
        exclude = ('personal_shopper', 'ordered_recently')

project/members/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from .forms import MemberForm
from .models import Member


class MemberCreateView(CreateView):
    form_class = MemberForm
    model = Member
    template_name = "members/form.html"


class MemberListView(ListView):
    model = Member
    template_name = "members/list.html"
    context_object_name = "members"


class MemberDetailView(DetailView):
    model = Member
    template_name = "members/detail.html"
    context_object_name = "member"

project/personal_shoppers/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from .models import PersonalShopper


class PersonalShopperCreateView(CreateView):
    model = PersonalShopper
    template_name = "personal_shoppers/form.html"


class PersonalShopperUpdateView(UpdateView):
    model = PersonalShopper
    template_name = "personal_shoppers/update.html"


class PersonalShopperListView(ListView):
    model = PersonalShopper
    template_name = "personal_shoppers/list.html"
    context_object_name = "p_shoppers"


class PersonalShopperDetailView(DetailView):
    model = PersonalShopper
    template_name = "personal_shoppers/detail.html"
    context_object_name = "p_shopper"

project/regions/views.py
from django.shortcuts import render

# Create your views here.

project/members/templates/members/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detail {{ member.first_name }} {{ member.last_name }}</h1>
    <a href="{% url "home" %}">Back to list</a>

    <p>Region: {{ member.region.name }}</p>
    <p>Phone number: {{ member.phone_number }}</p>
    <p>Ordered recently: {{ member.ordered_recently }}</p>
    <p>Personal Shopper: <a href="{{ member.personal_shopper.get_absolute_url }}">{{ member.personal_shopper.first_name }}</a></p>

    <h2>Orders</h2>
    <ul>
    {% for order in member.order_set.all  %}
    <li>{{ order.order_date }}</li>
    {% endfor %}
    </ul>

{% endblock content %}

project/members/templates/members/form.html
{% extends "base.html" %}

{% block content %}
    <h1>Register member</h1>
    <a href="{% url "home" %}">Back to list</a>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
    </form>
{% endblock content %}

project/members/templates/members/list.html
{% extends "base.html" %}


{% block content %}
    <h1>Members</h1>
    <a href="{% url "member_create" %}">Register member</a>

    <ul>
    {% for member in members %}
    <li><a href="{{member.get_absolute_url }}">{{ member.first_name }} {{ member.last_name }}</a></li>
    {% endfor %}
    </ul>

{% endblock content %}

project/personal_shoppers/templates/personal_shoppers/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ p_shopper.first_name }} {{ p_shopper.last_name }} <small>(<a href="{% url "p_shopper_update" p_shopper.pk  %}">Update</a>)</small></h1>
    <a href="{% url "p_shopper_list" %}">Back to list</a>

    <p>Shopper is active: {{ p_shopper.is_active }}</p>
    <p>Regions: {% for region in p_shopper.regions.all %}{{ region.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <h2>Assigned members</h2>
    <ul>
    {% for member in p_shopper.member_set.all %}
    <li><a href="{{ member.get_absolute_url }}">{{ member.first_name }} {{ member.last_name }}</a> {% if not member.ordered_recently %}(LEAD){% endif %}</li>
    {% endfor %}
    </ul>
{% endblock content %}

project/personal_shoppers/templates/personal_shoppers/form.html
{% extends "base.html" %}

{% block content %}
    <h1>Add personal shopper</h1>
    <a href="{% url "p_shopper_list" %}">Back to list</a>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
    </form>
{% endblock content %}

project/personal_shoppers/templates/personal_shoppers/list.html
{% extends "base.html" %}


{% block content %}
    <h1>Personal Shoppers</h1>
    <a href="{% url "p_shopper_create" %}">Add personal shopper</a>

    <ul>
    {% for p_shopper in p_shoppers %}
    <li><a href="{{p_shopper.get_absolute_url }}">{{ p_shopper.first_name }} {{ p_shopper.last_name }}</a> {% if not p_shopper.is_active %}(INACTIVE){% endif %}</li>
    {% endfor %}
    </ul>

{% endblock content %}

project/personal_shoppers/templates/personal_shoppers/update.html
{% extends "base.html" %}

{% block content %}
    <h1>Update personal shopper</h1>
    <a href="{% url "p_shopper_list" %}">Back to list</a>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
    </form>
{% endblock content %}

project/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url "home" %}">Members</a></li>
            <li><a href="{% url "p_shopper_list" %}">Personal shoppers</a></li>
        </ul>
    </nav>
</header>
<article>
    {% block content %}{% endblock content %}
</article>
</body>
</html>